kind: Service
apiVersion: v1
metadata:
  name: cluster-worker-0
spec:
  type: LoadBalancer
  selector:
    name: cluster
    job: worker
    task: "0"
  ports:
  - port: 5000
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: cluster-worker-0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cluster
        job: worker
        task: "0"
    spec:
      containers:

      - name: tensorflow
        image: tensorflow/tensorflow
        resources:
          limits:
            nvidia.com/gpu: 2

        env:

        - name: TF_CONFIG
          value: "{
                    \"cluster\": {\"worker\": [\"cluster-worker-0:5000\",\"cluster-worker-1:5000\"]},
                    \"task\": {
                    \"type\": \"worker\",
                    \"index\": \"0\"
                    }
                  }"

        ports:
        - containerPort: 5000

        command:
        - "/usr/bin/python"
        - "/train.py"

---

  
kind: Service
apiVersion: v1
metadata:
  name: cluster-worker-1
spec:
  type: LoadBalancer
  selector:
    name: cluster
    job: worker
    task: "1"
  ports:
  - port: 5000
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: cluster-worker-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cluster
        job: worker
        task: "1"
    spec:
      containers:

      - name: tensorflow
        image: tensorflow/tensorflow
        resources:
          limits:
            nvidia.com/gpu: 2

        env:

        - name: TF_CONFIG
          value: "{
                    \"cluster\": {\"worker\": [\"cluster-worker-0:5000\",\"cluster-worker-1:5000\"]},
                    \"task\": {
                    \"type\": \"worker\",
                    \"index\": \"0\"
                    }
                  }"

        ports:
        - containerPort: 5000

        command:
        - "/usr/bin/python"
        - "/train.py"

---
