apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

apiVersion: v1
kind: Service
metadata:
  name: cluster-worker-0
spec:
  type: LoadBalancer
  selector:
    name: cluster
    job: worker
    task: "0"
  ports:
  - port: 5000
---

apiVersion: v1
kind: Deployment
metadata:
  name: cluster-worker-0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cluster
        job: worker
        task: "0"
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      imagePullSecrets:
        - name: regcred
      containers:
      - name: tensorflow
        image: lreitsam/myrepo-01:latest
        # resources:
          # limits:
            # nvidia.com/gpu: 2
        env:
        - name: TF_CONFIG
          value: "{
                    \"cluster\": {\"worker\": [\"cluster-worker-0:5000\",\"cluster-worker-1:5000\"]},
                    \"task\": {
                    \"type\": \"worker\",
                    \"index\": \"0\"
                    }
                  }"
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/data_volume"
          name: task-pv-storage
        command:
        - "/usr/bin/python3"
        - "/usr/src/app/train.py"
---

apiVersion: v1
kind: Service
metadata:
  name: cluster-worker-1
spec:
  type: LoadBalancer
  selector:
    name: cluster
    job: worker
    task: "1"
  ports:
  - port: 5000

---

apiVersion: v1
kind: Deployment
metadata:
  name: cluster-worker-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cluster
        job: worker
        task: "1"
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      imagePullSecrets:
        - name: regcred
      containers:
      - name: tensorflow
        image: lreitsam/myrepo-01:latest
        # resources:
        #   limits:
            # nvidia.com/gpu: 2
        env:
        - name: TF_CONFIG
          value: "{
                    \"cluster\": {\"worker\": [\"cluster-worker-0:5000\",\"cluster-worker-1:5000\"]},
                    \"task\": {
                    \"type\": \"worker\",
                    \"index\": \"1\"
                    }
                  }"
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/data_volume"
          name: task-pv-storage
        command:
        - "/usr/bin/python3"
        - "/usr/src/app/train.py"

---

apiVersion: v1
kind: Service
metadata:
  name: cluster-tensorboard
spec:
  type: LoadBalancer
  selector:
    name: cluster
    job: tensorboard
    task: "2"
  ports:
  - port: 5000

---

apiVersion: v1
kind: Deployment
metadata:
  name: cluster-tensorboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cluster
        job: tensorboard
        task: "2"
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
      - name: tensorboard
        image: tensorflow/tensorflow
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/data_volume"
          name: task-pv-storage
        command:
        - "tensorboard"
        args:
        - "--logdir=/data_volume/logs/fit/"
        - "--port=5000"

---
